name: main

on:
  push:
  workflow_call:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install .[test]
      - name: Test with pytest
        run: pytest

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install Python build
        run: python3 -m pip install build --user
      - name: Build Python wheel and source tarball
        run: python3 -m build --sdist --wheel --outdir dist/
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist
