name: release

on:
  release:
    types: [ published ]

jobs:
  build:
    uses: jfsanchez91/props2yaml/.github/workflows/main.yml@build

  publish:
    name: Publish release to PyPi
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/props2yaml/
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist
      - name: Publish distribution 📦 to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
